### ISSUE TITLE
Harbor 2.0

### ISSUE THREAD

**Issue by ebesson** [p7t/actus#23]
https://github.com/goharbor/harbor/releases/tag/v2.0.0

**Comment by guilhem** [comment]
Ahah tu m'as devancé, je regardais les RC depuis un petit moment ;)

**Comment by guilhem** [comment]
@ebesson tu voudrais en parler ?

**Comment by ebesson** [comment]
@guilhem oui pas de problèmes !!!

**Comment by guilhem** [comment]
@ebesson On s'organise sur le discord pour la date ?
